/* Drop Indexes */

-- DROP INDEX IF EXISTS m_corporation_idx01;

/* Drop tables */
DROP TABLE IF EXISTS t_excel_media_info;

-- 他媒体情報を管理するテーブル。
CREATE TABLE t_excel_media_info
(
  no                      CHAR(20)                       ,
  file_name               VARCHAR(255)                   ,
  media_code              VARCHAR(10)                    ,
  media_name              VARCHAR(100)                   ,
  post_start_date         TEXT                           ,
  business_content        TEXT                           ,
  job                     TEXT                           ,
  corporation_name        TEXT                           ,
  zip_code                CHAR(10)                       ,
  addr_prefe              VARCHAR(256)                   ,
  address1                VARCHAR(400)                   ,
  address2                VARCHAR(400)                   ,
  address3                VARCHAR(400)                   ,
  tel                     CHAR(20)                       ,
  section                 TEXT                           ,
  corporation_emp_name    TEXT                           ,
  listed_marked           TEXT                           ,
  employee_number         TEXT                           ,
  capital_amount          TEXT                           ,
  year_sales              TEXT                           ,
  space                   TEXT                           ,
  job_category            VARCHAR(400)                   ,
  job_class               TEXT                           ,
  post_count              TEXT                           ,
  dispatch_flag           TEXT                           ,
  introduction_flag       TEXT                           ,
  flag_count              TEXT                           ,
  fax                     CHAR(20)                       ,
  data_get_date           TEXT                           ,
  mail_address            TEXT                           ,
  hp_url                  VARCHAR(500)                   ,
  representative_name     TEXT                           ,
  establish_date          TEXT                           ,
  option_work_form        TEXT                           ,
  option_appeal           TEXT                           ,
  premium_image_file      TEXT                           ,
  memo                    TEXT                           ,
  published_url           VARCHAR(500)                   ,
  billing_customer_code   TEXT                           ,
  comp_no                 TEXT                           ,
  media_type_details      TEXT                           ,
  work_location           TEXT                           ,
  allowance               TEXT                           ,
  working_hours           TEXT                           ,
  offer_no                CHAR(40)                       ,
  company_name_code       CHAR(40)                       ,
  char_icon               VARCHAR(400)                   ,
  edition                 VARCHAR(400)                   ,
  flag_space              VARCHAR(400)                   ,
  company_homepage        VARCHAR(500)                   ,
  edition_code            CHAR(40)                       ,
  ad_size_code            CHAR(40)                       ,
  nearest_station         VARCHAR(100)                   ,
  catch_copy              TEXT                           ,
  address_category        VARCHAR(400)                   ,
  celebration             VARCHAR(200)                   ,
  published_company_name  VARCHAR(80)                    ,
  published_address       VARCHAR(1000)                  ,
  twn_tel                 CHAR(20)                       ,
  twn_company_name        VARCHAR(80)                    ,
  converting_company_name VARCHAR(80)                    ,
  tokenize                VARCHAR(200)                   ,
  company_name_2          VARCHAR(80)                    ,
  other_2                 VARCHAR(400)                   ,
  branch_name_2           VARCHAR(80)                    ,
  pattern                 TEXT                           ,
  twm_address             VARCHAR(1000)                  ,
  converting_address      VARCHAR(1000)                  ,
  twn_serach_pref         VARCHAR(1000)                  ,
  other_media_pref        VARCHAR(1000)                  ,
  other_media_address_1   VARCHAR(400)                   ,
  other_media_address_2   VARCHAR(400)                   ,
  other_media_address_3   VARCHAR(400)                   ,
  term                    VARCHAR(1000)                  ,
  id                      CHAR(40)                       ,
  optional_item           TEXT                           ,
  create_date             DATETIME                       ,
  update_date             DATETIME                       ,
  delete_flag             BIT(1) DEFAULT FALSE NOT NULL  ,
  PRIMARY KEY  (no,file_name)
)ROW_FORMAT=DYNAMIC;